// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {CCIPReceiver} from "@chainlink/contracts-ccip/contracts/applications/CCIPReceiver.sol";
import {Client} from "@chainlink/contracts-ccip/contracts/libraries/Client.sol";
import {IRouterClient} from "@chainlink/contracts-ccip/contracts/interfaces/IRouterClient.sol";
import {Ownable} from "@openzeppelin/contracts/access/Ownable.sol";
import {Ownable2Step} from "@openzeppelin/contracts/access/Ownable2Step.sol";
import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import {SafeERC20} from "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import {ReentrancyGuard} from "@openzeppelin/contracts/utils/ReentrancyGuard.sol";

/// @notice One Hub for shop payments and fully prefunded, fixed-term staking positions.
/// @dev Rewards are a treasury-funded demo, NOT yield generated by CCIP.
contract PaymentHub is CCIPReceiver, Ownable2Step, ReentrancyGuard {
    using SafeERC20 for IERC20;

    struct Stake {
        address beneficiary;
        uint256 reward;
        uint64 lockDuration;
        uint64 unlockAt;
        uint64 sourceChainSelector;
        bool claimed;
    }

    address public immutable paymentToken;
    mapping(address => bool) public acceptedTokens;
    mapping(uint256 => address) public orderTokens;
    mapping(uint256 => uint256) public orderAmounts;
    mapping(uint256 => bool) public isOrderPaid;
    mapping(uint64 => bool) public allowedSourceChains;
    mapping(bytes32 => bool) public processedMessages;
    mapping(uint256 => Stake) public stakes;
    mapping(address => uint256) public rewardPool;
    // Includes unallocated rewards, committed rewards and delivered staking principal.
    mapping(address => uint256) public reservedBalances;

    error InvalidAddress();
    error InvalidOrder();
    error OrderAlreadyExists(uint256 orderId);
    error UnknownOrder(uint256 orderId);
    error OrderAlreadyPaid(uint256 orderId);
    error SourceChainNotAllowed(uint64 chainSelector);
    error InvalidMessageData();
    error InvalidSender();
    error InvalidTokenCount();
    error WrongToken(address token);
    error WrongAmount(uint256 expected, uint256 received);
    error MessageAlreadyProcessed(bytes32 messageId);
    error InsufficientRewardPool();
    error ReservedFunds();
    error StakeNotClaimable();
    error InsufficientFee(uint256 required, uint256 supplied);
    error RefundFailed();

    event OrderCreated(uint256 indexed orderId, address indexed token, uint256 amount);
    event TokenPermissionSet(address indexed token, bool allowed);
    event SourceChainPermissionSet(uint64 indexed chainSelector, bool allowed);
    event OrderPaid(uint256 indexed orderId, bytes32 indexed messageId, uint64 indexed sourceChainSelector, address payer, address token, uint256 amount);
    event FundsWithdrawn(address indexed token, address indexed recipient, uint256 amount);
    event RewardsFunded(address indexed token, uint256 amount);
    event StakeCreated(uint256 indexed orderId, address indexed beneficiary, uint256 reward, uint64 lockDuration);
    event StakeActivated(uint256 indexed orderId, uint64 unlockAt);
    event StakeClaimed(uint256 indexed orderId, uint256 amount, bytes32 messageId);

    constructor(address router, address token, address initialOwner) CCIPReceiver(router) Ownable(initialOwner) {
        if (router.code.length == 0 || token.code.length == 0) revert InvalidAddress();
        paymentToken = token;
        acceptedTokens[token] = true;
    }

    function createOrder(uint256 orderId, address token, uint256 amount) external onlyOwner {
        _createOrder(orderId, token, amount);
    }

    /// @notice Lock duration begins on destination delivery, not source transaction submission.
    function createStakingOrder(uint256 orderId, address token, uint256 principal, address beneficiary, uint256 reward, uint64 lockDuration) external onlyOwner {
        if (beneficiary == address(0) || lockDuration == 0 || lockDuration > 365 days) revert InvalidOrder();
        if (rewardPool[token] < reward) revert InsufficientRewardPool();
        _createOrder(orderId, token, principal);
        rewardPool[token] -= reward;
        stakes[orderId] = Stake(beneficiary, reward, lockDuration, 0, 0, false);
        emit StakeCreated(orderId, beneficiary, reward, lockDuration);
    }

    function _createOrder(uint256 orderId, address token, uint256 amount) private {
        if (!acceptedTokens[token]) revert WrongToken(token);
        if (orderId == 0 || amount == 0) revert InvalidOrder();
        if (orderAmounts[orderId] != 0) revert OrderAlreadyExists(orderId);
        orderAmounts[orderId] = amount;
        orderTokens[orderId] = token;
        emit OrderCreated(orderId, token, amount);
    }

    /// @dev Disabling a token blocks new orders, not payments already in transit.
    function setTokenAllowed(address token, bool allowed) external onlyOwner {
        if (token.code.length == 0) revert InvalidAddress();
        acceptedTokens[token] = allowed;
        emit TokenPermissionSet(token, allowed);
    }

    function setSourceChainAllowed(uint64 chainSelector, bool allowed) external onlyOwner {
        if (chainSelector == 0) revert SourceChainNotAllowed(chainSelector);
        allowedSourceChains[chainSelector] = allowed;
        emit SourceChainPermissionSet(chainSelector, allowed);
    }

    function fundRewards(address token, uint256 amount) external onlyOwner nonReentrant {
        if (!acceptedTokens[token] || amount == 0) revert InvalidOrder();
        uint256 beforeBalance = IERC20(token).balanceOf(address(this));
        IERC20(token).safeTransferFrom(msg.sender, address(this), amount);
        uint256 received = IERC20(token).balanceOf(address(this)) - beforeBalance;
        if (received != amount) revert WrongAmount(amount, received);
        rewardPool[token] += amount;
        reservedBalances[token] += amount;
        emit RewardsFunded(token, amount);
    }

    // CCIPReceiver.ccipReceive restricts entry to the immutable official router.
    function _ccipReceive(Client.Any2EVMMessage memory message) internal override {
        if (!allowedSourceChains[message.sourceChainSelector]) revert SourceChainNotAllowed(message.sourceChainSelector);
        if (processedMessages[message.messageId]) revert MessageAlreadyProcessed(message.messageId);
        if (message.data.length != 32) revert InvalidMessageData();
        if (message.sender.length != 32) revert InvalidSender();
        address payer = abi.decode(message.sender, (address));
        if (payer == address(0)) revert InvalidSender();
        uint256 orderId = abi.decode(message.data, (uint256));
        uint256 expected = orderAmounts[orderId];
        if (expected == 0) revert UnknownOrder(orderId);
        if (isOrderPaid[orderId]) revert OrderAlreadyPaid(orderId);
        if (message.destTokenAmounts.length != 1) revert InvalidTokenCount();
        Client.EVMTokenAmount memory received = message.destTokenAmounts[0];
        if (received.token != orderTokens[orderId]) revert WrongToken(received.token);
        if (received.amount != expected) revert WrongAmount(expected, received.amount);
        Stake storage stake = stakes[orderId];
        if (stake.beneficiary != address(0)) {
            if (payer != stake.beneficiary) revert InvalidSender();
            stake.unlockAt = uint64(block.timestamp) + stake.lockDuration;
            stake.sourceChainSelector = message.sourceChainSelector;
            reservedBalances[received.token] += received.amount;
            emit StakeActivated(orderId, stake.unlockAt);
        }
        processedMessages[message.messageId] = true;
        isOrderPaid[orderId] = true;
        emit OrderPaid(orderId, message.messageId, message.sourceChainSelector, payer, received.token, received.amount);
    }

    function withdraw(address token, address recipient, uint256 amount) external onlyOwner nonReentrant {
        if (recipient == address(0) || amount == 0) revert InvalidAddress();
        uint256 balance = IERC20(token).balanceOf(address(this));
        if (balance < reservedBalances[token] || amount > balance - reservedBalances[token]) revert ReservedFunds();
        IERC20(token).safeTransfer(recipient, amount);
        emit FundsWithdrawn(token, recipient, amount);
    }

    /// @notice Receive principal + reward directly on the Hub network.
    function claim(uint256 orderId) external nonReentrant {
        uint256 amount = _prepareClaim(orderId);
        IERC20(orderTokens[orderId]).safeTransfer(msg.sender, amount);
        emit StakeClaimed(orderId, amount, bytes32(0));
    }

    /// @notice Return principal + reward to the original payer on the original source network.
    /// @dev Call on the Hub; source-chain delivery is asynchronous. Native fee is separate.
    function claimCrossChain(uint256 orderId) external payable nonReentrant returns (bytes32 messageId) {
        uint256 amount = _prepareClaim(orderId);
        Client.EVM2AnyMessage memory message = _claimMessage(orderId, amount);
        IRouterClient router = IRouterClient(getRouter());
        uint64 destination = stakes[orderId].sourceChainSelector;
        uint256 fee = router.getFee(destination, message);
        if (msg.value < fee) revert InsufficientFee(fee, msg.value);
        IERC20 token = IERC20(orderTokens[orderId]);
        token.forceApprove(address(router), amount);
        messageId = router.ccipSend{value: fee}(destination, message);
        token.forceApprove(address(router), 0);
        if (msg.value > fee) {
            (bool refunded,) = msg.sender.call{value: msg.value - fee}("");
            if (!refunded) revert RefundFailed();
        }
        emit StakeClaimed(orderId, amount, messageId);
    }

    function quoteClaimFee(uint256 orderId) external view returns (uint256) {
        if (stakes[orderId].sourceChainSelector == 0) revert StakeNotClaimable();
        uint256 amount = orderAmounts[orderId] + stakes[orderId].reward;
        return IRouterClient(getRouter()).getFee(stakes[orderId].sourceChainSelector, _claimMessage(orderId, amount));
    }

    function _prepareClaim(uint256 orderId) private returns (uint256 amount) {
        Stake storage stake = stakes[orderId];
        if (msg.sender != stake.beneficiary || !isOrderPaid[orderId] || stake.claimed || block.timestamp < stake.unlockAt) revert StakeNotClaimable();
        amount = orderAmounts[orderId] + stake.reward;
        stake.claimed = true;
        reservedBalances[orderTokens[orderId]] -= amount;
    }

    function _claimMessage(uint256 orderId, uint256 amount) private view returns (Client.EVM2AnyMessage memory) {
        Client.EVMTokenAmount[] memory tokens = new Client.EVMTokenAmount[](1);
        tokens[0] = Client.EVMTokenAmount(orderTokens[orderId], amount);
        return Client.EVM2AnyMessage({
            receiver: abi.encode(stakes[orderId].beneficiary),
            data: "",
            tokenAmounts: tokens,
            feeToken: address(0),
            extraArgs: Client._argsToBytes(Client.GenericExtraArgsV2({gasLimit: 0, allowOutOfOrderExecution: true}))
        });
    }
}
