import { useEffect, useState } from 'react'
import { inspirations, navItems, partners, socials, strategies } from './content'

function Mark({ large = false }: { large?: boolean }) {
  return <span className={`brand-mark${large ? ' brand-mark-large' : ''}`} aria-hidden="true"><svg viewBox="0 0 64 64"><defs><linearGradient id="brandGradient" x1="0" y1="0" x2="1" y2="1"><stop stopColor="#49c9ff"/><stop offset="1" stopColor="#2673e9"/></linearGradient></defs><path d="M15 52V12h22c11 0 18 7 18 18s-7 18-18 18H27v4H15zm12-16h10c4 0 7-2 7-6s-3-6-7-6H27v12z" fill="url(#brandGradient)"/></svg></span>
}

function Logo() { return <a className="logo" href="#top" aria-label="POLYRUST home"><Mark/><span className="logo-type">POLYRUST</span></a> }

function Header() {
  const [open, setOpen] = useState(false)
  const [active, setActive] = useState('')
  useEffect(() => {
    const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) setActive(entry.target.id) }), { rootMargin: '-25% 0px -65% 0px' })
    navItems.forEach(([, id]) => { const el = document.getElementById(id); if (el) observer.observe(el) })
    return () => observer.disconnect()
  }, [])
  return <header className="site-header"><div className="header-inner"><Logo/><nav className={open ? 'main-nav is-open' : 'main-nav'} aria-label="Main navigation">{navItems.map(([label, id]) => <a key={id} className={active === id ? 'active' : ''} href={`#${id}`} onClick={() => setOpen(false)}>{label}</a>)}</nav><button className="wallet-button" type="button" disabled aria-label="Wallet connection will be available in a future release" title="Wallet integration is planned for a future release">Connect Wallet <span aria-hidden="true">↗</span></button><button className="menu-toggle" aria-label={open ? 'Close menu' : 'Open menu'} aria-expanded={open} onClick={() => setOpen(!open)}><span/><span/></button></div></header>
}

function Hero() {
  return <section className="hero" id="top"><div className="hero-orb" aria-hidden="true"><div className="orb-grid"/><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="orbit orbit-three"/><div className="orbit-node node-a"/><div className="orbit-node node-b"/><div className="orb-core"><Mark large/></div><div className="orb-caption">POLYRUST <span>·</span> INTELLIGENCE ENGINE</div></div><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-line"/> BUILT FOR WHAT'S NEXT</div><h1>Intelligence<br/>Behind <span>Prediction Markets</span></h1><p>An algorithmic platform built for automated trading on prediction markets. Combining real-time market analysis, adaptive strategies and advanced Web3 infrastructure to navigate a rapidly evolving digital economy.</p><div className="hero-note"><span className="pulse-dot"/> POLYRUST · WEB3 · PREDICTION MARKETS · AI TRADING</div></div><div className="hero-index">01 <span>—</span> 08</div></section>
}

function SectionHead({ label, title, children }: { label: string; title: string; children?: React.ReactNode }) { return <div className="section-head"><div className="eyebrow"><span className="eyebrow-line"/>{label}</div><h2>{title}</h2>{children}</div> }

function About() {
 return <section className="section about-section" id="about"><div className="about-editorial"><div className="about-intro"><SectionHead label="01 / ABOUT US" title="About Us"/><p className="about-lead">We created a decentralized platform with modern Web3 infrastructure, integrated with Polymarket — one of the largest prediction markets.</p><div className="about-body"><p>Our system uses an algorithmic trading bot that analyzes available markets and works with different strategies in the directions of Crypto, Sports, Politics and World Events.</p><p>Users do not need traditional registration or to provide personal data — simply connect a crypto wallet to access the platform.</p><p>Key operational processes are executed through predefined smart contract logic that automates specified conditions.</p></div><div className="about-bottom"><span>Web3 infrastructure.</span><span>Polymarket.</span><span>Algorithmic trading.</span><b>Result.</b></div><div className="about-stamp"><span className="stamp-icon"><Mark/></span><span>INDEPENDENT THINKING<br/>BUILT ON OPEN SYSTEMS</span></div></div></div><AboutArt/></section>
}

function AboutArt() { return <div className="about-art" aria-hidden="true"><div className="about-art-glow"/><div className="about-art-orbit about-orbit-a"/><div className="about-art-orbit about-orbit-b"/><div className="about-platform"><div className="platform-logo"><Mark large/><b>POLYRUST</b></div><div className="platform-panels"><span>◉<small>Sports</small></span><span>⌁<small>Crypto</small></span><span>◎<small>Politics</small></span><span>✳<small>World Events</small></span></div><div className="platform-base"/></div><i className="about-float float-a">◈</i><i className="about-float float-b">◌</i><i className="about-float float-c">✳</i><span className="about-art-caption">PREDICTION MARKETS · WEB3</span></div> }

function NetworkArt() { return <div className="network-art" aria-label="Abstract representation of connected market signals"><div className="network-grid"/><svg viewBox="0 0 600 240" role="img" aria-hidden="true"><path d="M25 165C105 165 92 75 180 75s74 91 162 91 76-75 144-75 73 52 101 52"/><path d="M25 195c89 0 87-50 159-50s90 52 159 52 79-53 140-53 81 31 104 31"/><path d="M80 41c68 0 65 71 126 71s71-49 127-49 69 60 125 60"/></svg><div className="network-center"><Mark large/></div>{['n1','n2','n3','n4','n5','n6'].map(n=><i key={n} className={`signal-node ${n}`}/>)}<span className="network-label label-a">SIGNAL FLOW <b>ACTIVE</b></span><span className="network-label label-b">MARKET DATA · REAL TIME</span></div> }

function Technology() {
 const items = [['01','Built with Rust','High-performance architecture designed for speed and efficient resource utilization.','↗'],['02','Real-Time Analysis','Continuous analysis of prediction-market data and changing market conditions.','◷'],['03','Adaptive Strategies','Dynamic adjustment of trading decisions based on current market signals.','⌁'],['04','Intelligent Risk Management','Exposure control, signal filtering and adaptive responses to market changes.','◇']]
 return <section className="section technology-section" id="technology"><div className="tech-top"><SectionHead label="02 / TECHNOLOGY" title="GEM RUST"><span className="section-subtitle">High-Performance HFT-Oriented Adaptive Trading Engine</span></SectionHead><p className="tech-intro">GEM RUST is a high-speed adaptive algorithmic trading bot built on an architecture oriented toward high-frequency trading (HFT). The system operates with Polymarket, analyzing market data in real time and dynamically adapting trading decisions to current market conditions.</p></div><NetworkArt/><div className="tech-lower"><div className="tech-explain"><p>The algorithm evaluates liquidity, trading flows, short-term momentum and volatility, automatically determining trade direction, position size and trading frequency.</p><p>Integrated risk management mechanisms provide exposure control, signal filtering, protection against unfavorable entries and adaptive hedging as market conditions change.</p></div><div className="tech-features">{items.map(([n,t,d,i])=><article className="feature-row" key={n}><span className="feature-number">{n}</span><div><h3>{t}</h3><p>{d}</p></div><span className="feature-icon">{i}</span></article>)}</div></div><div className="tech-ribbon"><span>HFT-Oriented Architecture</span><i/> <span>Ultra-Fast Market Response</span><i/> <span>Adaptive Algorithms</span><i/> <span>Intelligent Risk Management</span></div></section>
}

function StrategyArt({ kind }: { kind: string }) { return <div className={`strategy-art art-${kind}`} aria-hidden="true"><div className="art-halo"/><div className="art-line line-1"/><div className="art-line line-2"/><div className="art-line line-3"/><div className="art-symbol">{kind === 'sports' ? '◉' : kind === 'crypto' ? '⌁' : kind === 'politics' ? '◎' : '✳'}</div><span className="art-point point-1"/><span className="art-point point-2"/><span className="art-point point-3"/><span className="art-caption">{kind.toUpperCase()} / SIGNAL</span></div> }

function Strategies() { return <section className="section strategies-section" id="strategies"><SectionHead label="03 / STRATEGIES" title="Strategies"><p className="section-description">Purpose-built approaches for distinct markets. Each strategy adapts to changing signals and conditions.</p></SectionHead><div className="strategy-grid">{strategies.map((s,i)=><article className="strategy-card" key={s.name}><StrategyArt kind={s.kind}/><div className="strategy-info"><div className="card-meta"><span>{String(i+1).padStart(2,'0')}</span><span>{s.tag}</span></div><h3>{s.name}</h3><p>{s.text}</p><div className="card-foot"><span>ADAPTIVE STRATEGY</span><span className="arrow-mark">↗</span></div></div></article>)}</div></section> }

function PartnerNetwork() { return <div className="partner-network" aria-label="A central partner account connected with its network"><svg viewBox="0 0 400 310" aria-hidden="true"><path d="M200 155L77 66M200 155L200 42M200 155L324 66M200 155L78 246M200 155L200 267M200 155L322 246M77 66L200 42M200 42L324 66M78 246L200 267M200 267L322 246"/></svg><div className="partner-core"><Mark/><span>YOU</span></div>{[['p1','↗'],['p2','◌'],['p3','✳'],['p4','◉'],['p5','⌁'],['p6','◎']].map(([n,icon])=><div key={n} className={`partner-node ${n}`}>{icon}</div>)}<div className="network-tag">PARTNER NETWORK <b>CONNECTED</b></div><span className="network-orbit orbit-left"/><span className="network-orbit orbit-right"/></div> }

function Partners() { return <section className="section partners-section" id="partners"><div className="partner-layout"><div className="partner-copy"><SectionHead label="04 / PARTNER ECOSYSTEM" title="Partner Ecosystem"/><div className="grow-title">Grow <span>Together</span></div><p>A structured partner ecosystem designed to support long-term growth through a transparent, multi-level referral model.</p><div className="partner-footnote"><span className="footnote-icon">↗</span><span>Every level is available to partners from the start.</span></div></div><PartnerNetwork/><div className="levels-card"><div className="levels-heading"><div><span className="eyebrow-line"/> PROGRAM STRUCTURE</div><span>10 LEVELS</span></div><div className="levels-list">{partners.map((reward,i)=><div className="level-row" key={i}><span className="level-num">{String(i+1).padStart(2,'0')}</span><span className="level-name">Level {i+1}</span><span className="level-track"><i style={{width:`${Math.max(reward*10,12)}%`}}/></span><b>{reward}%</b></div>)}</div></div></div><div className="partner-disclosure"><span>01 —</span><p>Rewards are based on the investment of a partner at the corresponding level.</p><span>02 —</span><p>Referral rewards are funded from a dedicated partner balance, replenished by a portion of trading bot profits.</p></div></section> }

function Web3Cube() { return <div className="cube-scene" aria-label="Abstract transparent blockchain structure"><div className="cube-glow"/><div className="cube"><div className="cube-face face-front"/><div className="cube-face face-back"/><div className="cube-face face-left"/><div className="cube-face face-right"/><div className="cube-face face-top"/><div className="cube-face face-bottom"/><div className="cube-inner"/></div>{[['c1',1],['c2',2],['c3',3],['c4',4],['c5',5],['c6',6],['c7',7]].map(([c,n])=><i key={c} className={`cube-node ${c}`}>{n}</i>)}<span className="cube-orbit cube-orbit-a"/><span className="cube-orbit cube-orbit-b"/><span className="cube-caption">VERIFIABLE BY DESIGN</span></div> }

function Transparency() { return <section className="section transparency-section" id="transparency"><div className="transparency-copy"><SectionHead label="05 / TRANSPARENCY & WEB3" title="Transparency & Web3"/><p>The platform is built on Web3 principles, where interaction takes place directly through a crypto wallet — without traditional registration or the need to provide personal data.</p><p>Key operational processes are implemented through smart contracts with predefined logic. Once deployed, the conditions and execution logic can be verified directly on the blockchain.</p><p>Users can independently verify the smart contract address, its code and transaction history, as well as review how the specified operations are executed.</p><div className="trust-points">{['On-Chain Verification','Transparent Logic','Non-Custodial Access'].map((x,i)=><span key={x}><b>0{i+1}</b>{x}<i>↗</i></span>)}</div></div><Web3Cube/></section> }

function Inspirations() { return <section className="section inspiration-section" id="inspirations"><SectionHead label="06 / INSPIRATIONS" title="Inspirations"><p className="section-description">People and projects shaping the way we think about prediction markets and information.</p></SectionHead><div className="inspiration-grid">{inspirations.map((x,i)=><article className="inspiration-card" key={x.name}><div className={'portrait portrait-' + (i+1)}><img src="/inspirations-triptych.webp" style={{ left: x.imagePosition }} alt={`Illustrated portrait representing ${x.name}`} loading="lazy"/><span className="portrait-index">0{i+1}</span><span className="portrait-label">EDITORIAL ILLUSTRATION</span></div><div className="inspiration-copy"><div className="inspiration-role">{x.role}</div><h3>{x.name}</h3><p>{x.text}</p><span className="inspiration-tag">{x.tag}</span></div></article>)}</div><p className="inspiration-note">The individuals and projects shown are presented for informational and inspirational purposes only. No partnership, endorsement or affiliation is implied.</p></section> }

function SocialIcon({ type }: { type: string }) { return type === 'instagram' ? <svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3.5" y="3.5" width="17" height="17" rx="5"/><circle cx="12" cy="12" r="4"/><circle className="icon-fill" cx="17.7" cy="6.5" r="1"/></svg> : <svg viewBox="0 0 24 24" aria-hidden="true"><path className="icon-fill" d="M21.5 4.1 18.3 19c-.24 1.05-.86 1.3-1.75.81l-4.84-3.57-2.34 2.25c-.26.26-.47.47-.97.47l.35-4.93 8.97-8.1c.39-.35-.09-.55-.6-.2L6.04 12.8 1.3 11.32c-1.03-.32-1.05-1.03.22-1.53L20.05 2.6c.85-.31 1.59.2 1.45 1.5Z"/></svg> }

function Footer() { return <footer className="footer"><div className="footer-main"><div className="footer-brand"><Logo/><p>Algorithmic Intelligence<br/>for Prediction Markets.</p><div className="social-links">{socials.map(s=><a key={s.href} href={s.href} target="_blank" rel="noopener noreferrer" aria-label={s.label} title={s.label}><SocialIcon type={s.icon}/></a>)}</div></div><nav className="footer-nav" aria-label="Footer navigation">{navItems.map(([label,id])=><a key={id} href={`#${id}`}>{label}<span>↗</span></a>)}</nav><div className="footer-aside"><span className="footer-status"><i/> PUBLIC SITE</span><span className="footer-url">POLYRUST.NET<br/>GLOBAL · WEB3</span></div></div><div className="footer-bottom"><span>© 2026 POLYRUST. All rights reserved.</span><span>ALGORITHMIC INTELLIGENCE FOR PREDICTION MARKETS</span><a href="#top" aria-label="Back to top">BACK TO TOP ↑</a></div></footer> }

export default function App() { return <><Header/><main><Hero/><About/><Technology/><Strategies/><Partners/><Transparency/><Inspirations/></main><Footer/></> }
