import { useEffect, useState } from 'react'
import { inspirations, navItems, partners, socials, strategies } from './content'

function Mark({ large = false }: { large?: boolean }) {
  return <span className={`brand-mark${large ? ' brand-mark-large' : ''}`} aria-hidden="true"><svg viewBox="0 0 64 64"><path d="M15 52V12h22c11 0 18 7 18 18s-7 18-18 18H27v4H15zm12-16h10c4 0 7-2 7-6s-3-6-7-6H27v12z" fill="currentColor"/></svg></span>
}

function Logo() { return <a className="logo" href="#top" aria-label="POLYRUST home"><Mark/><span className="logo-type">POLYRUST</span></a> }

function Header() {
  const [open, setOpen] = useState(false)
  const [active, setActive] = useState('')
  useEffect(() => {
    const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) setActive(entry.target.id) }), { rootMargin: '-25% 0px -65% 0px' })
    navItems.forEach(([, id]) => { const el = document.getElementById(id); if (el) observer.observe(el) })
    return () => observer.disconnect()
  }, [])
  return <header className="site-header"><div className="header-inner"><Logo/><nav className={open ? 'main-nav is-open' : 'main-nav'} aria-label="Main navigation">{navItems.map(([label, id]) => <a key={id} className={active === id ? 'active' : ''} href={`#${id}`} onClick={() => setOpen(false)}>{label}</a>)}</nav><button className="wallet-button" type="button" disabled aria-label="Wallet connection will be available in a future release" title="Wallet integration is planned for a future release">Connect Wallet <span aria-hidden="true">↗</span></button><button className="menu-toggle" aria-label={open ? 'Close menu' : 'Open menu'} aria-expanded={open} onClick={() => setOpen(!open)}><span/><span/></button></div></header>
}

function Hero() {
  return <section className="hero" id="top"><div className="hero-symbol" aria-hidden="true"><Mark large/><span>POLYRUST / INTELLIGENCE ENGINE</span></div><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-line"/> BUILT FOR WHAT'S NEXT</div><h1>Intelligence<br/>Behind <span>Prediction Markets</span></h1><p>An algorithmic platform built for automated trading on prediction markets. Combining real-time market analysis, adaptive strategies and advanced Web3 infrastructure to navigate a rapidly evolving digital economy.</p><div className="hero-actions"><a className="button button-primary" href="#technology">Explore the engine <span>↗</span></a><a className="button button-secondary" href="#strategies">View strategies <span>→</span></a></div></div><div className="hero-index"><span>THE PLATFORM</span><p>Built with Rust.<br/>Connected to Polymarket.<br/>Designed for Web3.</p><span>INDEPENDENT BY DESIGN ↗</span></div><div className="hero-note">RUST <span>×</span> POLYMARKET <span>×</span> WEB3 <span>×</span> ALGORITHMIC INTELLIGENCE</div></section>
}

function SectionHead({ label, title, children }: { label: string; title: string; children?: React.ReactNode }) { return <div className="section-head"><div className="eyebrow"><span className="eyebrow-line"/>{label}</div><h2>{title}</h2>{children}</div> }

function About() {
 return <section className="section about-section" id="about"><div className="about-editorial"><div className="about-intro"><SectionHead label="01 / ABOUT US" title="About Us"/><p className="about-lead">We created a decentralized platform with modern Web3 infrastructure, integrated with Polymarket — one of the largest prediction markets.</p><div className="about-body"><p>Our system uses an algorithmic trading bot that analyzes available markets and works with different strategies in the directions of Crypto, Sports, Politics and World Events.</p><p>Users do not need traditional registration or to provide personal data — simply connect a crypto wallet to access the platform.</p><p>Key operational processes are executed through predefined smart contract logic that automates specified conditions.</p></div><div className="about-bottom"><span>Web3 infrastructure.</span><span>Polymarket.</span><span>Algorithmic trading.</span><b>Result.</b></div><div className="about-stamp"><span className="stamp-icon"><Mark/></span><span>INDEPENDENT THINKING<br/>BUILT ON OPEN SYSTEMS</span></div></div></div><AboutArt/></section>
}

function AboutArt() { return <div className="about-art"><div className="panel-heading"><span>PLATFORM ARCHITECTURE</span><span>01 / OVERVIEW</span></div><div className="architecture-source">Crypto wallet <span>↗</span></div><div className="architecture-connector"/><div className="architecture-engine"><Mark/><div>POLYRUST<small>ALGORITHMIC INTELLIGENCE</small></div></div><div className="architecture-connector"/><div className="platform-panels">{['Sports', 'Crypto', 'Politics', 'World Events'].map(x => <span key={x}>{x}</span>)}</div><div className="panel-footer"><span>MARKET INTEGRATION</span><span>Polymarket ↗</span></div></div> }

function NetworkArt() { return <div className="network-art"><div className="panel-heading"><span>GEM RUST / ENGINE WORKFLOW</span><span>ILLUSTRATIVE</span></div><div className="workflow">{['Market data', 'Signal analysis', 'Risk controls', 'Adaptive execution'].map((x, i) => <div className="workflow-step" key={x}><span>0{i + 1}</span><h3>{x}</h3><span className="workflow-arrow" aria-hidden="true">→</span></div>)}</div><div className="terminal"><div><span>▲</span> gem_rust::engine</div><p><span>✓</span> Analyze liquidity, momentum and volatility</p><p><span>✓</span> Evaluate exposure and filter market signals</p><p><span>✓</span> Adapt position size and trading frequency</p><div className="terminal-caption">CONCEPTUAL WORKFLOW — NOT LIVE TRADING OUTPUT</div></div></div> }

function Technology() {
 const items = [['01','Built with Rust','High-performance architecture designed for speed and efficient resource utilization.','↗'],['02','Real-Time Analysis','Continuous analysis of prediction-market data and changing market conditions.','◷'],['03','Adaptive Strategies','Dynamic adjustment of trading decisions based on current market signals.','⌁'],['04','Intelligent Risk Management','Exposure control, signal filtering and adaptive responses to market changes.','◇']]
 return <section className="section technology-section" id="technology"><div className="tech-top"><SectionHead label="02 / TECHNOLOGY" title="GEM RUST"><span className="section-subtitle">High-Performance HFT-Oriented Adaptive Trading Engine</span></SectionHead><p className="tech-intro">GEM RUST is a high-speed adaptive algorithmic trading bot built on an architecture oriented toward high-frequency trading (HFT). The system operates with Polymarket, analyzing market data in real time and dynamically adapting trading decisions to current market conditions.</p></div><NetworkArt/><div className="tech-lower"><div className="tech-explain"><p>The algorithm evaluates liquidity, trading flows, short-term momentum and volatility, automatically determining trade direction, position size and trading frequency.</p><p>Integrated risk management mechanisms provide exposure control, signal filtering, protection against unfavorable entries and adaptive hedging as market conditions change.</p></div><div className="tech-features">{items.map(([n,t,d,i])=><article className="feature-row" key={n}><span className="feature-number">{n}</span><div><h3>{t}</h3><p>{d}</p></div><span className="feature-icon">{i}</span></article>)}</div></div><div className="tech-ribbon"><span>HFT-Oriented Architecture</span><i/> <span>Ultra-Fast Market Response</span><i/> <span>Adaptive Algorithms</span><i/> <span>Intelligent Risk Management</span></div></section>
}

function StrategyArt({ kind }: { kind: string }) { return <div className={`strategy-art art-${kind}`} aria-hidden="true"><div className="art-halo"/><div className="art-line line-1"/><div className="art-line line-2"/><div className="art-line line-3"/><div className="art-symbol">{kind === 'sports' ? '◉' : kind === 'crypto' ? '⌁' : kind === 'politics' ? '◎' : '✳'}</div><span className="art-point point-1"/><span className="art-point point-2"/><span className="art-point point-3"/><span className="art-caption">{kind.toUpperCase()} / SIGNAL</span></div> }

function Strategies() { return <section className="section strategies-section" id="strategies"><SectionHead label="03 / STRATEGIES" title="Strategies"><p className="section-description">Purpose-built approaches for distinct markets. Each strategy adapts to changing signals and conditions.</p></SectionHead><div className="strategy-grid">{strategies.map((s,i)=><article className="strategy-card" key={s.name}><StrategyArt kind={s.kind}/><div className="strategy-info"><div className="card-meta"><span>{String(i+1).padStart(2,'0')}</span><span>{s.tag}</span></div><h3>{s.name}</h3><p>{s.text}</p><div className="card-foot"><span>ADAPTIVE STRATEGY</span><span className="arrow-mark">↗</span></div></div></article>)}</div></section> }

function PartnerNetwork() { return <div className="partner-network" aria-label="A central partner account connected with its network"><svg viewBox="0 0 400 310" aria-hidden="true"><path d="M200 155L77 66M200 155L200 42M200 155L324 66M200 155L78 246M200 155L200 267M200 155L322 246M77 66L200 42M200 42L324 66M78 246L200 267M200 267L322 246"/></svg><div className="partner-core"><Mark/><span>YOU</span></div>{[['p1','↗'],['p2','◌'],['p3','✳'],['p4','◉'],['p5','⌁'],['p6','◎']].map(([n,icon])=><div key={n} className={`partner-node ${n}`}>{icon}</div>)}<div className="network-tag">PARTNER NETWORK <b>CONNECTED</b></div><span className="network-orbit orbit-left"/><span className="network-orbit orbit-right"/></div> }

function Partners() { return <section className="section partners-section" id="partners"><div className="partner-layout"><div className="partner-copy"><SectionHead label="04 / PARTNER ECOSYSTEM" title="Partner Ecosystem"/><div className="grow-title">Grow <span>Together</span></div><p>A structured partner ecosystem designed to support long-term growth through a transparent, multi-level referral model.</p><div className="partner-footnote"><span className="footnote-icon">↗</span><span>Every level is available to partners from the start.</span></div></div><PartnerNetwork/><div className="levels-card"><div className="levels-heading"><div><span className="eyebrow-line"/> PROGRAM STRUCTURE</div><span>10 LEVELS</span></div><div className="levels-list">{partners.map((reward,i)=><div className="level-row" key={i}><span className="level-num">{String(i+1).padStart(2,'0')}</span><span className="level-name">Level {i+1}</span><span className="level-track"><i style={{width:`${Math.max(reward*10,12)}%`}}/></span><b>{reward}%</b></div>)}</div></div></div><div className="partner-disclosure"><span>01 —</span><p>Rewards are based on the investment of a partner at the corresponding level.</p><span>02 —</span><p>Referral rewards are funded from a dedicated partner balance, replenished by a portion of trading bot profits.</p></div></section> }

function Web3Cube() { return <div className="verification-card"><div className="panel-heading"><span>WEB3 / PRINCIPLES</span><span>↗</span></div><Mark large/><h3>Don't trust.<br/>Verify.</h3><p>Open systems. Predefined logic.<br/>Independent verification.</p><div className="verification-list">{['Smart contract code', 'Execution logic', 'Transaction history'].map((x,i) => <div key={x}><span>0{i+1}</span>{x}<span>↗</span></div>)}</div><span className="verification-caption">VERIFIABLE BY DESIGN</span></div> }

function Transparency() { return <section className="section transparency-section" id="transparency"><div className="transparency-copy"><SectionHead label="05 / TRANSPARENCY & WEB3" title="Transparency & Web3"/><p>The platform is built on Web3 principles, where interaction takes place directly through a crypto wallet — without traditional registration or the need to provide personal data.</p><p>Key operational processes are implemented through smart contracts with predefined logic. Once deployed, the conditions and execution logic can be verified directly on the blockchain.</p><p>Users can independently verify the smart contract address, its code and transaction history, as well as review how the specified operations are executed.</p><div className="trust-points">{['On-Chain Verification','Transparent Logic','Non-Custodial Access'].map((x,i)=><span key={x}><b>0{i+1}</b>{x}<i>↗</i></span>)}</div></div><Web3Cube/></section> }

function Inspirations() { return <section className="section inspiration-section" id="inspirations"><SectionHead label="06 / INSPIRATIONS" title="Inspirations"><p className="section-description">People and projects shaping the way we think about prediction markets and information.</p></SectionHead><div className="inspiration-grid">{inspirations.map((x,i)=><article className="inspiration-card" key={x.name}><div className="inspiration-monogram" aria-hidden="true"><span>0{i+1} / INSPIRATION</span><div>{x.name.split(' ').map(word => word[0]).join('')}</div></div><div className="inspiration-copy"><div className="inspiration-role">{x.role}</div><h3>{x.name}</h3><p>{x.text}</p><span className="inspiration-tag">{x.tag}</span></div></article>)}</div><p className="inspiration-note">The individuals and projects shown are presented for informational and inspirational purposes only. No partnership, endorsement or affiliation is implied.</p></section> }

function SocialIcon({ type }: { type: string }) { return type === 'instagram' ? <svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3.5" y="3.5" width="17" height="17" rx="5"/><circle cx="12" cy="12" r="4"/><circle className="icon-fill" cx="17.7" cy="6.5" r="1"/></svg> : <svg viewBox="0 0 24 24" aria-hidden="true"><path className="icon-fill" d="M21.5 4.1 18.3 19c-.24 1.05-.86 1.3-1.75.81l-4.84-3.57-2.34 2.25c-.26.26-.47.47-.97.47l.35-4.93 8.97-8.1c.39-.35-.09-.55-.6-.2L6.04 12.8 1.3 11.32c-1.03-.32-1.05-1.03.22-1.53L20.05 2.6c.85-.31 1.59.2 1.45 1.5Z"/></svg> }

function Footer() { return <footer className="footer"><div className="footer-main"><div className="footer-brand"><Logo/><p>Algorithmic Intelligence<br/>for Prediction Markets.</p><div className="social-links">{socials.map(s=><a key={s.href} href={s.href} target="_blank" rel="noopener noreferrer" aria-label={s.label} title={s.label}><SocialIcon type={s.icon}/></a>)}</div></div><nav className="footer-nav" aria-label="Footer navigation">{navItems.map(([label,id])=><a key={id} href={`#${id}`}>{label}<span>↗</span></a>)}</nav><div className="footer-aside"><span className="footer-status"><i/> PUBLIC SITE</span><span className="footer-url">POLYRUST.NET<br/>GLOBAL · WEB3</span></div></div><div className="footer-bottom"><span>© 2026 POLYRUST. All rights reserved.</span><span>ALGORITHMIC INTELLIGENCE FOR PREDICTION MARKETS</span><a href="#top" aria-label="Back to top">BACK TO TOP ↑</a></div></footer> }

export default function App() { return <><Header/><main><Hero/><About/><Technology/><Strategies/><Partners/><Transparency/><Inspirations/></main><Footer/></> }
